a=int(input("enter a number:"))
b=int(input("enter another number:"))
print ('the sum is:',a+b)
print ('the difference is:',a-b)
print ('the product is:',a*b)
print ('the quotient is:',a/b)
print ('the floor quotient is:',a//b)
print ('the remainder is:',a%b)
print ('the exponential value is:',a+b)
